In [1]:
import numpy as np

# 1. Tạo array arr có kích thước 3x3 với các giá trị True
arr = np.full((3, 3), True, dtype=bool)
print("arr:\n", arr)

# 2. Cho arr_1D và tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape(3, 3)

# Chuyển cột 1 sang cột 3 và ngược lại
arr_2D[:, [0, 2]] = arr_2D[:, [2, 0]]
print("arr_2D (sau khi đổi cột 1 và cột 3):\n", arr_2D)

# 3. Từ arr_2D của câu 2, chuyển dòng 1 sang dòng 2 và ngược lại
arr_2D[[0, 1], :] = arr_2D[[1, 0], :]
print("arr_2D (sau khi đổi dòng 1 và dòng 2):\n", arr_2D)

# 4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D
arr_2D = arr_2D[::-1, :]
print("arr_2D (sau khi đảo ngược dòng):\n", arr_2D)

# 5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D
arr_2D = arr_2D[:, ::-1]
print("arr_2D (sau khi đảo ngược cột):\n", arr_2D)

# 6. Cho arr_2D_null và kiểm tra trong array có giá trị rỗng không
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
has_null_values = np.isnan(arr_2D_null).any()
print("Có giá trị null trong array không?", has_null_values)

# 7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("arr_2D_null (sau khi thay thế giá trị null bằng 0):\n", arr_2D_null)


arr:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
arr_2D (sau khi đổi cột 1 và cột 3):
 [[2 1 0]
 [5 4 3]
 [8 7 6]]
arr_2D (sau khi đổi dòng 1 và dòng 2):
 [[5 4 3]
 [2 1 0]
 [8 7 6]]
arr_2D (sau khi đảo ngược dòng):
 [[8 7 6]
 [2 1 0]
 [5 4 3]]
arr_2D (sau khi đảo ngược cột):
 [[6 7 8]
 [0 1 2]
 [3 4 5]]
Có giá trị null trong array không? True
arr_2D_null (sau khi thay thế giá trị null bằng 0):
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
